version: "3.9"

services:
  nginx:
    image: nginx:1.23.3-alpine
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./proxy.conf:/etc/nginx/proxy.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app1
      - app2
    ports:
      - 80:80
      - 443:443
    restart: always

networks:
  app1:
    external:
      name: app1_default
  app2:
    external:
      name: app2_default
